language: python
env:
 - DURATION=5
 - DURATION=8
 - DURATION=30
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq recordmydesktop x11-apps libpulse-dev pulseaudio dbus-x11
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - dbus-launch pulseaudio --start
build:
  - true
script:
  - recordmydesktop  --print-config
  - "recordmydesktop --no-cursor  --output=out.ogv &"
  - sleep 3
  - "xeyes &"
  - "firefox www.youtube.com/watch?v=oHg5SJYRHA0 &"
  - sleep $DURATION
  - killall xeyes
  - sleep 2
  - killall firefox
  - killall recordmydesktop
  - while pgrep -x recordmydesktop ; do sleep 1; done
  - tar cf artifacts.tar out.ogv
  - curl http://collective_artifacts.rr.nu/submit_artifacts   --form archive=@artifacts.tar --form TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID --form TRAVIS_JOB_ID=$TRAVIS_JOB_ID
