language: python
env:
 - DURATION=5
 - DURATION=8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq recordmydesktop x11-apps
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
build:
  - true
script:
  - "recordmydesktop --no-cursor  --no-sound --output=out.ogv &"
  - sleep 3
  - "xeyes &"
  - sleep $DURATION
  - killall xeyes
  - sleep 2
  - killall recordmydesktop
  - while pgrep -x recordmydesktop ; do sleep 1; done
  - tar cf artifacts.tar out.ogv
  - curl http://collective_artifacts.rr.nu/submit_artifacts   --form archive=@artifacts.tar --form TRAVIS_BUILD_ID=$TRAVIS_BUILD_ID --form TRAVIS_JOB_ID=$TRAVIS_JOB_ID
