language: python
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq recordmydesktop x11-apps
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
build:
  - true
script:
  - "recordmydesktop  --no-sound --output=out.ogv &"
  - "xeyes & sleep 4 ; kill %1"
  - killall recordmydesktop; fg
  - tar cf out.ogv artifacts.tar
  - curl http://collective_artifacts.rr.nu/submit_artifacts   --form archive=@artifacts.tar --form TRAVIS_JOB_ID=$TRAVIS_JOB_ID
